version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019
  - Ubuntu
configuration: Release
test: off
build_script:
  - ps: ./Build.ps1
  - ps: ./BuildNativeUWP.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh build.sh
artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: Koq5UhgDHkK7NgoFMwKE+NH8l3E/YmRSgnokN9lTGJ38gJ62VWyiXauHi7KLQ3sH
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifacts:
    /Serilog.*\.nupkg/
    /Serilog.*\.snupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
