version: '{build}'
skip_tags: true
image:
  - Visual Studio 2022
  - Ubuntu
configuration: Release
test: off
build_script:
- pwsh: |
    if ($isWindows)
    {
      Invoke-WebRequest https://dot.net/v1/dotnet-install.ps1 -OutFile ./dotnet-install.ps1
      ./dotnet-install.ps1 -InstallDir 'C:\Program Files\dotnet'
    }
    else
    {
      Invoke-WebRequest https://dot.net/v1/dotnet-install.sh -OutFile ./dotnet-install.sh
      sudo chmod u+x dotnet-install.sh
      if ($isMacOS)
      {
        sudo ./dotnet-install.sh --install-dir /usr/local/share/dotnet
      }
      else
      {
        sudo ./dotnet-install.sh --install-dir /usr/share/dotnet
      }
    }
- dotnet build --configuration Release --nologo
- dotnet test --configuration Release --no-build --no-restore --nologo
artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: 45/vGyNCdoOvWSorcVX6qYM3oC/mCBj0CDRXNZP4twlIrBiZ9sKtKMdHwufm4ogS
  on:
    branch: /^(main|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifacts:
    /Serilog.*\.nupkg/
    /Serilog.*\.snupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: main
